# Generated by Django 4.1.7 on 2023-03-12 18:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image/avatar_user/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телеграм ID'),
        ),
    ]
