# Generated by Django 4.1.7 on 2023-03-12 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('gender', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default='Man', max_length=6, verbose_name='Пол')),
                ('info', models.CharField(max_length=512, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
