# Generated by Django 4.1.7 on 2023-03-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertg',
            name='user_tg_id',
            field=models.IntegerField(unique=True, verbose_name='Телеграм ID'),
        ),
    ]
