# Generated by Django 4.1.7 on 2023-03-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_usertg_user_tg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-create_date',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
