# Generated by Django 4.1.7 on 2023-03-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='Чат ID'),
        ),
    ]
