# Generated by Django 4.1.7 on 2023-03-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Email верификация', 'verbose_name_plural': 'Email верификация'},
        ),
    ]
